packages:
  - name: accelerate
    version: 0.21.0
  - name: peft
    version: 0.4.0
  - name: bitsandbytes
    version: 0.40.2
  - name: transformers
    version: 4.31.0
  - name: trl
    version: 0.4.7
