packages:
  - name: accelerate
    version: 0.21.0
  - name: peft
    version: 0.4.0
  - name: bitsandbytes
    version: 0.40.2
  - name: transformers
    version: 4.31.0
  - name: trl
    version: 0.4.7
  - name: py_midicsv
    version: 4.0.0
  - name: mido
    version: 1.3.2
  - name: llmlingua
    version: 0.2.1
  - name: tqdm
  - name: pandas
